name: task_management_application
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  provider: ^6.0.3
  http: ^0.13.3
  date_picker_timeline: ^1.2.3
  dropdown_button2: ^1.7.2
  percent_indicator: ^4.2.2
  animated_bottom_navigation_bar: ^1.1.0
  flutter_datetime_picker: ^1.5.1
  syncfusion_flutter_calendar: ^20.2.50
  flutter_slidable: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-Regular.ttf
